"""init_mvp_core

Revision ID: 06d2eaa12721
Revises: 
Create Date: 2026-08-10 15:25:00.727379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06d2eaa12721'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('google_id', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('OWNER', 'VET', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('specializations', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('license_number', sa.String(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('verification_status', postgresql.ENUM('PENDING', 'VERIFIED', 'REJECTED', 'SUSPENDED', name='verification_status'), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('is_accepting_appointments', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_doctor_profiles_specialty'), 'doctor_profiles', ['specialty'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_verification_status'), 'doctor_profiles', ['verification_status'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('gender', postgresql.ENUM('MALE', 'FEMALE', 'UNKNOWN', name='pet_gender'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('existing_conditions', sa.Text(), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pets_owner_id'), 'pets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_pets_species'), 'pets', ['species'], unique=False)
    op.create_table('consultation_offerings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_profile_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('VIDEO', 'AUDIO', 'CHAT', name='consultation_type'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_profile_id', 'type')
    )
    op.create_index(op.f('ix_consultation_offerings_doctor_profile_id'), 'consultation_offerings', ['doctor_profile_id'], unique=False)
    op.create_index(op.f('ix_consultation_offerings_type'), 'consultation_offerings', ['type'], unique=False)
    op.create_table('doctor_availabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_profile_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('start_time', sa.SmallInteger(), nullable=False),
    sa.Column('end_time', sa.SmallInteger(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_profile_id', 'day_of_week', 'start_time', 'end_time')
    )
    op.create_index(op.f('ix_doctor_availabilities_day_of_week'), 'doctor_availabilities', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_doctor_availabilities_doctor_profile_id'), 'doctor_availabilities', ['doctor_profile_id'], unique=False)
    op.create_index('ix_doctor_availabilities_profile_day', 'doctor_availabilities', ['doctor_profile_id', 'day_of_week'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('doctor_profile_id', sa.UUID(), nullable=False),
    sa.Column('consultation_offering_id', sa.UUID(), nullable=True),
    sa.Column('consultation_type', postgresql.ENUM('VIDEO', 'AUDIO', 'CHAT', name='consultation_type'), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('price_at_booking', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='appointment_status'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by_user_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consultation_offering_id'], ['consultation_offerings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_doctor_scheduled_start', 'appointments', ['doctor_profile_id', 'scheduled_start'], unique=False)
    op.create_index('ix_appointments_owner_status', 'appointments', ['owner_id', 'status'], unique=False)
    op.create_index('ix_appointments_scheduled_start', 'appointments', ['scheduled_start'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('payer_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_appointment_id'), 'payments', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_payer_id'), 'payments', ['payer_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_payer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_index(op.f('ix_payments_appointment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index('ix_appointments_scheduled_start', table_name='appointments')
    op.drop_index('ix_appointments_owner_status', table_name='appointments')
    op.drop_index('ix_appointments_doctor_scheduled_start', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_doctor_availabilities_profile_day', table_name='doctor_availabilities')
    op.drop_index(op.f('ix_doctor_availabilities_doctor_profile_id'), table_name='doctor_availabilities')
    op.drop_index(op.f('ix_doctor_availabilities_day_of_week'), table_name='doctor_availabilities')
    op.drop_table('doctor_availabilities')
    op.drop_index(op.f('ix_consultation_offerings_type'), table_name='consultation_offerings')
    op.drop_index(op.f('ix_consultation_offerings_doctor_profile_id'), table_name='consultation_offerings')
    op.drop_table('consultation_offerings')
    op.drop_index(op.f('ix_pets_species'), table_name='pets')
    op.drop_index(op.f('ix_pets_owner_id'), table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_doctor_profiles_verification_status'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_specialty'), table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
